from tkinter import *

root = Tk()
root.title("Calculator-RRJ")
root.geometry("245x440")


root.minsize(width= 245, height= 440)
root.maxsize(width= 245, height= 440)
root.configure(background="antiquewhite")
def click(event):
    global scvalue
    text = event.widget.cget("text")
    print(text)
    if text=="=" :
        if scvalue.get().isdigit():
            value= int(scvalue.get())
        else:
            value= eval(scvalue.get())
        scvalue.set(value)
        screen.update()
    elif text=="AC":
        scvalue.set("")
    else:
        scvalue.set(scvalue.get()+ text)
        screen.update()
scvalue = StringVar()
scvalue.set("")
screen = Entry(root, text= scvalue, font="Lucida 40 bold", bg="darkseagreen4", fg="white")
screen.pack(ipadx=12,padx = 7, pady=7)
f0 = Frame(root, borderwidth= 3, bg="antiquewhite")
b = Button(f0,  text= "AC",bg="gray30", fg="white", font=(" oswald 11 bold"), padx= 17, pady= 17)
b.pack(side= LEFT)
b.bind("<Button-1>", click)
b = Button(f0, text= "%",bg="bisque1", font=(" oswald 11 bold"), padx= 20, pady= 17)
b.pack(side= LEFT)
b.bind("<Button-1>", click)
b = Button(f0, text= "/",bg="bisque1", font=(" oswald 11 bold"), padx= 22, pady= 17)
b.pack(side= LEFT)
b.bind("<Button-1>", click)
b = Button(f0, text= "*",bg="bisque1", font=(" oswald 11 bold"), padx= 22, pady= 17)
b.pack(side= LEFT)
b.bind("<Button-1>", click)
f0.pack(anchor="nw")
f1 = Frame(root, borderwidth= 3, bg="antiquewhite")
for i in range (7,10):
    b = Button(f1, text= f"{i}",bg="antiquewhite3",fg= "white", font=(" oswald 12 bold"), padx= 22, pady= 17)
    b.pack(side= LEFT)
    b.bind("<Button-1>", click)
b = Button(f1, text= "-",bg="bisque1", font=(" oswald 21 bold"), padx= 23,pady=2)
b.pack(side= LEFT)
b.bind("<Button-1>", click)
f1.pack(anchor="nw")
f2 = Frame(root, borderwidth= 3, bg="antiquewhite")
for i in range (4,6):
    b = Button(f2, text=f"{i}",bg="antiquewhite3",fg= "white", font=(" oswald 12 bold"), padx= 21, pady= 17)
    b.pack(side= LEFT)
    b.bind("<Button-1>", click)
b= Button(f2,text= "6",bg="antiquewhite3",fg= "white", font=(" oswald 12 bold"), padx= 22, pady= 17 )
b.pack(side= LEFT)
b.bind("<Button-1>", click)
b = Button(f2, text= "+",bg="bisque1", font=(" oswald 21 bold"), padx= 22,pady=2)
b.pack(side= LEFT)
b.bind("<Button-1>", click)
f2.pack(anchor="nw")
f3 = Frame(root, borderwidth= 3, bg="antiquewhite")
for i in range (1,4):
    b = Button(f3, text=f"{i}",bg="antiquewhite3",fg= "white", font=(" oswald 12 bold"), padx= 22, pady= 17)
    b.pack(side= LEFT)
    b.bind("<Button-1>", click)
b = Button(f3, text= ".",bg="bisque1", font=(" oswald 21 bold"), padx= 22,pady=2)
b.pack(side= LEFT)
b.bind("<Button-1>", click)
f3.pack(anchor="nw")
f4 = Frame(root, borderwidth= 3, bg="antiquewhite")
b = Button(f4, text= "0",bg= "aquamarine3", font=(" oswald 12 bold"), padx= 51.5, pady= 17)
b.pack(side= LEFT)
b.bind("<Button-1>", click)
b = Button(f4, text= "=",bg= "aquamarine3", font=(" oswald 20 bold"), padx= 51.5)
b.pack(side= LEFT)
b.bind("<Button-1>", click)
f4.pack(anchor="nw")

root.mainloop()